### ISSUE TITLE
Proponuję usunąć Panda

### ISSUE THREAD

**Issue by northpl93** [TheMolkaPL/FunnyGuilds#1]
I tak nic z tym nie idzie zrobić, a tylko niepotrzebnie zwiększa rozmiar pluginu.

**Comment by TheMolkaPL** [comment]
Nie wiem czy jest to gdzieś używane. Jeżeli nie to można.

**Comment by MrGregorix** [comment]
Panda rulz!

**Comment by Dzikoysk** [comment]
#nope

**Comment by TheMolkaPL** [comment]
https://github.com/Dzikoysk/FunnyGuilds/commit/fb546155522edda8c53c89db7e7d7e5e7c16d230

**Comment by Dzikoysk** [comment]
Nadal jest wymagana! Tylko ta w fg była przestarzała

**Comment by TheMolkaPL** [comment]
@Dzikoysk proponuję oba projekty oprzeć o Maven. Pandę dodać jako dependency do FunnyGuilds.

**Comment by Dzikoysk** [comment]
Tia, już przy tej wersji 4.0 pre z przed 3 miesięcy miałem to zrobić i tak jakoś wyszło... :>

**Comment by ToMatch** [comment]
@TheMolkaPL Dodaj fg w .jar bo nie wiem co mam zrobić z .zip

**Comment by TheMolkaPL** [comment]
@ToMatch musisz skompilować to samemu.

**Comment by ToMatch** [comment]
@TheMolkaPL jak masz jakiś poradnik ? (Nie łatwiej podać linku)

**Comment by TheMolkaPL** [comment]
Nigdy taki z mojej strony nie powstanie. Kiedyś widziałem go na MPCgównie, napisany przez @Thefilippop1PL, ale szukaj sam i **uważaj na Blezura!**
