### ISSUE TITLE
Co się różni?

### ISSUE THREAD

**Issue by aysx** [TheMolkaPL/FunnyGuilds#3]
Cześć, mam pytanie, czym się różni ten plugin od oryginalnego fg? Bo jak przejrzałem kod(z połowe bo dużo tego jest) to prawie taki sam, a craftbukkit 1.7.2 jest uzywany więc ten plugin nie jest chyba pod 1.8...

**Comment by TheMolkaPL** [comment]
[Tutaj](https://github.com/TheMolkaPL/FunnyGuilds/commits/mc1.8) możesz śledzić zmiany jakie są nanoszone na ten plugin.

Celem tego projektu jest aktualizowanie zawieszonego projektu FunnyGuilds pod najnowsze wersje serwera Bukkit oraz Spigot.

Dlaczego niby 1.7.2?

``` xml
<dependency>
    <groupId>org.spigotmc</groupId>
    <artifactId>spigot-api</artifactId>
    <version>1.8.6-R0.1-SNAPSHOT</version>
</dependency>
<dependency>
    <groupId>tc.oc</groupId>
    <artifactId>sportbukkit</artifactId>
    <version>1.8-R0.1-SNAPSHOT</version>
</dependency>
```

https://github.com/TheMolkaPL/FunnyGuilds/blob/mc1.8/pom.xml#L32-L41
