### ISSUE TITLE
Fork?

### ISSUE THREAD

**Issue by NotJustPizza** [TheMolkaPL/FunnyGuilds#4]
Ten fork jest oficjalną kontynuacją pluginu? Czy rozwija się niezależnie od oficjalnego FunnyGuilds?

**Comment by TheMolkaPL** [comment]
Nieoficjalny, stabilny FunnyGuilds 3.9.9.1 zaktualizowany do Minecraft 1.8.\* - bez tablisty. :)

**Comment by SlimaKCoder** [comment]
Baza taka sama dla tego forka jak rozumiem? Po  za tym ogólnie były jakieś zmiany SQL w FunnyGuilds ostatnimi czasy? Mam jeszcze gdzieś starą bazę i chciałem ją wykorzystać ;)
