### ISSUE TITLE
Strona do updatera zwraca 403.

### ISSUE THREAD

**Issue by SocketByte** [TheMolkaPL/FunnyGuilds#7]
`[FunnyGuilds] Server returned HTTP response code: 403 for URL: http://www.dzikoysk.net/projects/funnyguilds/latest.info`

Coś zwaliłem czy wina po stronie Dzikiego?

**Comment by dzikoysk** [comment]
Pewnie u mnie. Wczoraj wieczorem zmieniałem u siebie adresy DNS serwerów. Do jutra wszystko powinno wrócić do normy.

**Comment by dzikoysk** [comment]
@TheMolkaPL powinieneś dodać User-Agenta w IOUtils, bo inaczej nie pobierze contentu

https://github.com/dzikoysk/FunnyGuilds/blob/master/src/main/java/net/dzikoysk/funnyguilds/util/IOUtils.java#L36

Na razie nie puszczam po CloudFlare, bo widzę, że brak User-Agenta uwali kilka rzeczy :/

**Comment by TheMolkaPL** [comment]
Gotowe! <3 :)
